### ISSUE TITLE
[Bug] Overlay position resets after disconnecting from call

### ISSUE THREAD

**Issue by derN3rd** [Naozumi520/Remedy#8] opened 2022-09-12 11:58 UTC
Hey there,

In **Remedy Pro 1.1.4** (on MacOS 12.5.1) whenever I unpin the overlay and move it to a new position it gets reset after disconnecting from the call and joining into a new one.

### Steps to reproduce:
- Open Remedy Pro
- Join into a Channel on Discord
- Click 'Unpin overlay' in the taskbar menu
- Move the overlay to a new position
- Click 'Pin overlay' in the taskbar menu
- Disconnect from discord channel
- Reconnect to discord channel
- Position is reset now

Thanks in advance

**Comment by Naozumi520** [comment] 2022-09-13 17:27
Fixed in https://github.com/Naozumi520/Remedy/commit/724864e28805b7b8b166a8a1fc3a0c916e8d8025 and released as [Remedy Pro 1.1.5](https://github.com/Naozumi520/Remedy/releases/tag/RemedyPro1.1.5).

This seems to be caused by a small mistake. School was a little busy so the fix came late, sorry about that!

**Comment by Naozumi520** [comment] 2022-09-13 17:27
Closed as [fixed](https://github.com/Naozumi520/Remedy/commit/724864e28805b7b8b166a8a1fc3a0c916e8d8025).

**Closed as completed by Naozumi520** 2022-09-13 17:27 UTC
Labels: bug
