### ISSUE TITLE
Arm64

### ISSUE THREAD

**Issue by damonemo** [Naozumi520/Remedy#12] opened 2022-12-28 14:08 UTC
When I downloaded the arm64 one I get this message. 

<img width="261" alt="Screenshot 2022-12-28 at 9 06 48 AM" src="https://user-images.githubusercontent.com/75283377/209824517-fc688ea4-b57c-4623-8d33-0cff6df814fe.png">

**Comment by Naozumi520** [comment] 2022-12-29 13:59
It seems that electron-builder has issue building arm64 app. I can try build a universal version later so Remedy will work on both x64 and arm64. But package size is going to be an issue, and has been around for a long time as well... 😭

**Comment by Naozumi520** [comment] 2023-02-25 16:35
Can you try this package (1.1.8 pre-release)?

https://cdn.discordapp.com/attachments/939482444778864663/1079079296901054484/Remedy_Pro-1.1.7-universal.dmg.zip

**Comment by damonemo** [comment] 2023-02-25 16:39
It works

**Comment by Naozumi520** [comment] 2023-02-25 16:42
Nice! I will publish this version then. 😋

**Comment by damonemo** [comment] 2023-02-25 17:26
OK wait it's not working. The overlay is not working but the app and login
works if that makes sense

**Comment by Naozumi520** [comment] 2023-02-26 04:54
Hmm, can you try restarting the app and try again? I got it once during testing, but couldn't reproduce it.

**Comment by Naozumi520** [comment] 2023-02-26 04:57
Ah, I see the problem. Will be fixed in release.

**Comment by damonemo** [comment] 2023-02-26 14:53
Do you have the fix version?

**Comment by Naozumi520** [comment] 2023-02-26 15:01
Not yet. But the problem has been confirmed and I'm going to fix it when I have the time.

**Comment by Naozumi520** [comment] 2023-03-21 09:53
Hello! I released the version [1.1.8](https://github.com/Naozumi520/Remedy/releases/tag/RemedyPro1.1.8), which includes all the fixes, please take a look!

Edited: Hold on, I'm sorry that the app got some issue after packing. I will keep you update asap!

**Comment by damonemo** [comment] 2023-03-22 00:29
you didn't put the download up '-'

**Comment by Naozumi520** [comment] 2023-03-22 07:53
Yep, the app got some issue after packing. I will keep you update ASAP.

**Comment by damonemo** [comment] 2023-04-09 14:07
1.1.2 should be the one I download correct?

**Comment by Naozumi520** [comment] 2023-04-09 14:39
Yes, 1.1.2 is the updated standard version. Pro version is now having issue.

**Comment by Naozumi520** [comment] 2023-04-28 05:37
Fixed in 2.0

**Closed as completed by Naozumi520** 2023-04-28 05:37 UTC
